# Generated by Django 4.2.2 on 2023-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user1',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
