# Generated by Django 4.2.2 on 2023-07-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdts', '0002_tbl_user1_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user1',
            name='photo',
        ),
    ]
